[package]
name = "logic-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
serde_json = "1.0"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["console"] }

symphonia = { version = "0.5", features = ["all-codecs", "all-formats"] }
rustfft = "6.1"
tract-onnx = "0.21"
getrandom = { version = "0.2", features = ["js"] }
# ffmpeg-next = { version = "6.0", features = ["all"] } # This will be configured later

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.scripts]
build = "wasm-pack build --target web --out-dir ../frontend/src/lib/wasm/logic-engine"

