[package]
name = "audio-stretcher"
version = "0.1.0"
edition = "2024"

[dependencies]

wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
getrandom = { version = "0.2", features = ["js"] }

[build-dependencies]
cc = "1.0"

bindgen = "0.69"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.scripts]
build = "wasm-pack build --target web --out-dir ../frontend/src/lib/wasm/audio-stretcher"

